### ISSUE TITLE
output of large bignum breaks the stream

### ISSUE THREAD

**Issue by Dinosky** [akovalenko/sbcl-win32-threads#12]
Output of long bignum/string breaks the stream of _terminal-io_. e.g.

(expt 12345 12345)

Changing +bytes-per-buffer+ in fd-stream.lisp back to (\* 4 1024) solves the problem.  Don't know why larger buffer caused the problem.

**Comment by akovalenko** [comment]
Does it happen on windows console only? Recent commit a4ceddf5fc2f1c28dea7bf7febef692d7da9b1f4 should fix it (there is a small limit for WriteConsole).

**Comment by Dinosky** [comment]
I have only tried it on Windows 7 64 console.  No problem if the output is diverted to files.  The commit fixed the problem.  Thanks.
