### ISSUE TITLE
degradation performance

### ISSUE THREAD

**Issue by bach741974** [akovalenko/sbcl-win32-threads#16]
Win32, Win64

I see degradation performance in loop when add :from 0 :

CL-USER> (time (let ((n 1))

```
         (loop :for i :from 0 :upto 500000000 :by n
            :do
            (* i 8))))
```

Evaluation took:
 4.578 seconds of real time
 4.578125 seconds of total run time (4.578125 user, 0.000000 system)
 100.00% CPU
 13,778,114,497 processor cycles
 33,016 bytes consed

NIL
CL-USER> (time (let ((n 1))

```
         (loop :for i  :upto 500000000 :by n
            :do
            (* i 8))))
```

Evaluation took:
 0.391 seconds of real time
 0.390625 seconds of total run time (0.390625 user, 0.000000 system)
 100.00% CPU
 1,175,092,867 processor cycles
 0 bytes consed

NIL
CL-USER>

**Comment by bach741974** [comment]
The same problem:

CL-USER> (time (let ((n 1))
          (do ((i 0 (+ i n)))
              ((> i 500000000))
           (\* i 8))))
Evaluation took:
  0.391 seconds of real time
  0.375000 seconds of total run time (0.375000 user, 0.000000 system)
  95.91% CPU
  1,181,206,875 processor cycles
  0 bytes consed

NIL
CL-USER> (defun f () 1)
F
CL-USER> (time (let ((n (f)))  
         (do ((i 0 (+ i n)))  
              ((> i 500000000))
           (\* i 8))))
Evaluation took:
  4.594 seconds of real time
  4.546875 seconds of total run time (4.546875 user, 0.000000 system)
  98.98% CPU
  13,824,936,712 processor cycles
  0 bytes consed

NIL
CL-USER>

**Comment by akovalenko** [comment]
Non-uniform performance for semantically equivalent code is not a bug (the opposite requirement is impossible in general case). You may think of it as an unexpected optimization in the faster case, instead of an unexpected degradation in the slower one, so it feels better.

The second example `(let ((n (f)))...)` can be improved by declaiming F inline, so SBCL is allowed to derive a type of n (actually, it will open-code 1 as constant in this case). The first example probably gets an extra SETF in the expansion if you add :from 0, and SBCL's type inference is known to be impeded by SETFs.

**Comment by bach741974** [comment]
I agree with you for the second example. 

In first 

(let ((n 1))

```
     (loop :for i  :upto 500000000 :by n
        :do
        (* i 8)))
```

expands  to 

(LET ((N 1))
  (BLOCK NIL
    (LET ((#:LOOP-STEP-BY-1411 N) (I 0))
      (DECLARE (TYPE (AND NUMBER REAL) I)
               (TYPE (AND NUMBER (REAL (0))) #:LOOP-STEP-BY-1411))
      (TAGBODY
       SB-LOOP::NEXT-LOOP
        (IF (> I '500000000)
            (PROGN (GO SB-LOOP::END-LOOP))
            NIL)
        (\* I 8)
        (SETQ I (+ I #:LOOP-STEP-BY-1411))
        (GO SB-LOOP::NEXT-LOOP)
       SB-LOOP::END-LOOP))))

The version with :from 0  expands to 

(LET ((N 1))
  (BLOCK NIL
    (LET ((I 0) (#:LOOP-STEP-BY-1409 N))
      (DECLARE (TYPE (AND NUMBER (REAL (0))) #:LOOP-STEP-BY-1409)
               (TYPE (AND REAL NUMBER) I))
      (TAGBODY
       SB-LOOP::NEXT-LOOP
        (IF (> I '500000000)
            (PROGN (GO SB-LOOP::END-LOOP))
            NIL)
        (\* I 8)
        (SETQ I (+ I #:LOOP-STEP-BY-1409))
        (GO SB-LOOP::NEXT-LOOP)
       SB-LOOP::END-LOOP))))

They expand to equivalent code. So it seems as issue. Maybe I am wrong.
