### ISSUE TITLE
(the (values double-float double-float) ... doesn't work as expected

### ISSUE THREAD

**Issue by syakovyn** [akovalenko/sbcl-win32-threads#17]
Hello,

I have the following code 

(the (values double-float double-float) (let ((result (ffloor 1d0 1d0))) result))

that throws an exception:
Value set
  [1.0d0]
from RESULT in
  (THE (VALUES DOUBLE-FLOAT DOUBLE-FLOAT)
       (LET (#)
         RESULT))
is not of type
  (VALUES DOUBLE-FLOAT DOUBLE-FLOAT &REST T).
   [Condition of type SIMPLE-TYPE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [TERMINATE-THREAD] Terminate this thread (#<THREAD "repl-thread" RUNNING {1003BC8083}>)

 Though, when I use (the (values double-float double-float) 1.0d0) it works well. Somehow involving "let" changes the things drastically.

Thanks,
Serhiy Y

**Comment by akovalenko** [comment]
As far as the Standard goes, `(the (values double-float double-float) 1.0d0)` is undefined behavior. In SBCL, as you see, it seems to do no harm for a constant, but detects the error for more complicated forms like your example involving LET. 

As you probably know, `(the (values double-float double-float) (let ((result (ffloor 1d0 1d0))) result))` is undefined behavior as well. Each variable is a one-value place, so secondary result of ffloor is thrown away instantly. You have to use MULTIPLE-VALUE-BIND, not LET, to bind secondary value to a distinct variable.

Therefore RESULT inside LET evaluates to one value, so does the form under THE. `(THE DOUBLE-FLOAT (LET ...))` would be correct.

**Comment by syakovyn** [comment]
Thank you. I see. 

Actually what I can see is the consequence of the following things (http://www.lispworks.com/documentation/HyperSpec/Body/s_the.htm#the):
1. Missing values are treated as nil for the purposes of checking their types.
2. The consequences are undefined if any result is not of the declared type.
3. NIL is not of the type double-float.

I would expect it to be more logical, that is to throw an exception in both cases or allow it in both cases. 
But that is beyond of the standard :(
