### ISSUE TITLE
(open "file" :direction :output :if-exists nil) broken

### ISSUE THREAD

**Issue by quicklisp** [akovalenko/sbcl-win32-threads#3]
I just tried sbcl-1.0.48.8.290.wth.kovalenko-x86.msi and got the following unexpected behavior:

```
(progn
  (close (open "foo.txt" :direction :probe :if-does-not-exist :create)) 
  (open "foo.txt" :direction :output :if-exists nil))
```

This produced an error instead of the expected value NIL.

**Comment by akovalenko** [comment]
Should be fixed in current binaries (x86/msi is http://archive.siftsoft.com/sbcl/sbcl-1.0.48.35.299.wth.kovalenko-x86.msi); relevant commit: 7ce345697e9c13198422ce4e14968fd412c969a7.

**Comment by akovalenko** [comment]
...Please confirm if it works for you. Thanks for the report.

**Comment by quicklisp** [comment]
Works for me.
