### ISSUE TITLE
Segfault if SBCL_HOME is not defined

### ISSUE THREAD

**Issue by markokocic** [akovalenko/sbcl-win32-threads#5]
The problem is that when **SBCL_HOME** is not present, sbcl assumes that
core is located in the same dir as exe file (logical assumption for
windows platform).

**sh install.sh** on windows is copying sbcl.exe and sbcl.core in different folders.
If I manually copy sbcl.exe to the same folder where sbcl.core is and
start is from there, it works correctly.

In runtime.c, **search_for_core** function inside **LISP_FEATURE_WIN32** block there is the
following snippet:

```
           core = copied_existing_filename_or_null(lookhere);
           return core;
```

copied_existing_filename_or_null returns 0 in case file can't be found.

There is a 0 check at the end of the method, but it this case it is
bypassed by early return.

**Comment by akovalenko** [comment]
Should be addressed by commit 6fcd487d61218f1a3739.
Sorry, proceeded to fix it my way before noticing your patch (anyway, single return path seems better).

**Comment by markokocic** [comment]
Agree, single return path makes more sense.

Also, do you plan to update install.sh to copy sbcl.exe into the same folder as sbcl.core?

**Comment by akovalenko** [comment]
I'd prefer not to touch install.sh. I don't use it on Windows and Wine: building MSI seems to be the right way for this platform. So far, using install.sh on Windows has only a single advantage: we get a distribution with the same directory structure as other binary distributions. As a downside, you have to take care on SBCL_HOME for it to work. 

But if directory structure would be _different_ from other binary distributions of SBCL, I'd see no point in using install.sh at all.
