### ISSUE TITLE
x86-64 installer doesn't include asdf

### ISSUE THREAD

**Issue by acelent** [akovalenko/sbcl-win32-threads#8]
```
* (require 'asdf)

debugger invoked on a SB-INT:EXTENSION-FAILURE in thread #<THREAD
                                                           "initial thread" RUNNING
                                                            {10029B1381}>:
  Don't know how to REQUIRE ASDF.
See also:
  The SBCL Manual, Variable *MODULE-PROVIDER-FUNCTIONS*
  The SBCL Manual, Function REQUIRE

Type HELP for debugger help, or (SB-EXT:QUIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(SB-IMPL::REQUIRE-ERROR "Don't know how to ~S ~A." REQUIRE ASDF)
0] 
```

I worked around this issue by unpacking the files from the 32-bit installer and deleting the fasl.

**Comment by akovalenko** [comment]
Thanks for reporting.
The problem should go away since SBCL-1.0.51.27.mswinmt.942 (binaries uploaded recently). If you have some time, please verify this fact (feel free to close the issue if everything's alright now).

**Comment by acelent** [comment]
Thanks for the fast response. Just tested, it's good now.

I don't want to close this issue because I believe there's a problem that is probably solved in the same way (build configuration).

The contribs don't have precompiled fasls like the official release, so I always get an error compiling sb-introspect when I lauch this fork of SBCL with SLIME. This happens because SBCL's Swank backend requires it, so it gets compiled and it tries to write the resuling fasls in the contrib's dir. This occurs when running without administrator priviledges.

**Comment by akovalenko** [comment]
You're right about the problem (thank you for reporting it, too).

I've uploaded SBCL build 1.0.51.31.mswinmt.945, where the problem should go away: it should have the same set of precompiled FASLS as an official release (I'm gradually switching back from local build hacks to the upstream build system, and it's the result of fully-invoked make-target-contrib.sh).

**Comment by acelent** [comment]
Yes, it seems perfect! I'm closing this issue.
